/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.keyvault.models;

import com.azure.common.http.HttpResponse;
import com.azure.common.http.rest.RestException;

/**
 * Exception thrown for an invalid response with KeyVaultError information.
 */
public final class KeyVaultErrorException extends RestException {
    /**
     * Initializes a new instance of the KeyVaultErrorException class.
     *
     * @param message the exception message or the response content if a message is not available.
     * @param response the HTTP response.
     */
    public KeyVaultErrorException(String message, HttpResponse response) {
        super(message, response);
    }

    /**
     * Initializes a new instance of the KeyVaultErrorException class.
     *
     * @param message the exception message or the response content if a message is not available.
     * @param response the HTTP response.
     * @param body the deserialized response body.
     */
    public KeyVaultErrorException(String message, HttpResponse response, KeyVaultError body) {
        super(message, response, body);
    }

    @Override
    public KeyVaultError body() {
        return (KeyVaultError) super.body();
    }
}
